'use client';

import { useState, useEffect } from 'react';

function formatCurrency(val: number) {
 return '₹' + val.toLocaleString('en-IN', { maximumFractionDigits: 0 });
}

export default function AdminShiftReportsPage() {
 const [reports, setReports] = useState<any[]>([]);
 const [loading, setLoading] = useState(true);
 const [generating, setGenerating] = useState(false);
 const [selectedDate, setSelectedDate] = useState(new Date().toISOString().split('T')[0]);

 const fetchReports = async () => {
 try {
 const res = await fetch('/api/admin/shift-reports');
 const data = await res.json();
 setReports(data.reports || []);
 } catch (err) { console.error(err); }
 finally { setLoading(false); }
 };

 useEffect(() => { fetchReports(); }, []);

 const handleGenerate = async () => {
 setGenerating(true);
 try {
 const res = await fetch('/api/admin/shift-reports', {
 method: 'POST',
 headers: { 'Content-Type': 'application/json' },
 body: JSON.stringify({ shiftType: 'full_day' }),
 });
 if (res.ok) fetchReports();
 } catch (err) { console.error(err); }
 finally { setGenerating(false); }
 };

 if (loading) return (
 <div>
 <h1 className="text-2xl font-bold text-white mb-6">Shift Reports</h1>
 <div className="space-y-3">{Array.from({ length: 3 }).map((_, i) => <div key={i} className="h-24 bg-white/5 border-2 border-white/10 animate-pulse" />)}</div>
 </div>
 );

 return (
 <div>
 <div className="flex items-start justify-between mb-6">
 <div>
 <h1 className="text-2xl font-bold text-white">Shift Reports</h1>
 <p className="text-sm text-white/50 mt-1">End-of-shift summaries and handover reports.</p>
 </div>
 <button onClick={handleGenerate} disabled={generating}
 className="px-4 py-2.5 bg-accent text-white text-sm font-medium shadow-blue-500/20 hover:bg-accent/80 disabled:opacity-70 transition-all">
 {generating ? 'Generating...' : '📋 Generate Report'}
 </button>
 </div>

 {reports.length === 0 ? (
 <div className="bg-white/5 border-2 border-white/10 p-12 text-center">
 <p className="text-white/40 mb-3">No shift reports generated yet.</p>
 <button onClick={handleGenerate} className="text-accent text-sm font-medium hover:underline">Generate your first report</button>
 </div>
 ) : (
 <div className="space-y-4">
 {reports.map((r: any) => (
 <div key={r._id} className="bg-white/5 border-2 border-white/10 p-6 ">
 <div className="flex items-start justify-between mb-4">
 <div>
 <h3 className="font-semibold text-white">
 {new Date(r.shiftDate).toLocaleDateString('en-IN', { weekday: 'long', day: 'numeric', month: 'long', year: 'numeric' })}
 </h3>
 <p className="text-xs text-white/40 mt-0.5 capitalize">{r.shiftType?.replace(/_/g, ' ')} shift • Generated by {r.generatedBy}</p>
 </div>
 <span className="text-[10px] text-white/40">{new Date(r.generatedAt).toLocaleTimeString('en-IN', { hour: '2-digit', minute: '2-digit' })}</span>
 </div>

 <div className="grid grid-cols-2 sm:grid-cols-5 gap-3 mb-4">
 <div className="bg-accent/10 p-3 text-center">
 <p className="text-xs text-accent font-medium">Received</p>
 <p className="text-xl font-bold text-accent">{r.ordersReceived}</p>
 </div>
 <div className="bg-green-500/100/10 p-3 text-center">
 <p className="text-xs text-green-400 font-medium">Completed</p>
 <p className="text-xl font-bold text-green-400">{r.ordersCompleted}</p>
 </div>
 <div className="bg-red-500/10 p-3 text-center">
 <p className="text-xs text-red-400 font-medium">Rejected</p>
 <p className="text-xl font-bold text-red-400">{r.ordersRejected}</p>
 </div>
 <div className="bg-yellow-500/100/10 p-3 text-center">
 <p className="text-xs text-yellow-400 font-medium">SLA Breaches</p>
 <p className="text-xl font-bold text-yellow-400">{r.slaBreaches}</p>
 </div>
 <div className="bg-purple-500/10 p-3 text-center">
 <p className="text-xs text-purple-500 font-medium">Revenue</p>
 <p className="text-lg font-bold text-purple-400">{formatCurrency(r.totalRevenue)}</p>
 </div>
 </div>

 {r.summary && <p className="text-sm text-white/60 bg-white/5 p-3 mb-3">{r.summary}</p>}

 {r.supplierIssues?.length > 0 && (
 <div>
 <p className="text-[10px] text-red-400 uppercase tracking-wider font-semibold mb-2">Supplier Issues</p>
 <div className="space-y-1">
 {r.supplierIssues.map((s: any, i: number) => (
 <div key={i} className="flex items-center gap-2 text-xs text-white/60 bg-red-500/10/50 px-3 py-2 ">
 <span className="w-1.5 h-1.5 bg-red-400 rounded-full" />
 <span className="font-medium">{s.supplierName}:</span>
 <span>{s.issue}</span>
 </div>
 ))}
 </div>
 </div>
 )}
 </div>
 ))}
 </div>
 )}
 </div>
 );
}
